# Generated by Django 4.2.4 on 2023-08-23 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DATA', models.DateField()),
                ('MOVIMENTACAO', models.TextField()),
                ('VALOR', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
